### ISSUE TITLE
How to generate address offline?

### ISSUE THREAD

**Issue by Wangmmx** [MetacoinPlatform/metacoin-api#1]
How is the generation from the public key to the address completed? I did not find the relevant code. In addition, through the method `createAddress` in the api docs, I have been reporting an error message: `3103, Public key decode error`. Is the format incorrect? There is a corresponding Example of publicKey? 

Here is my publicKey 
`"-----BEGIN PUBLIC KEY-----\\nMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXr9/YDqS3HoOKuXqRZU5zDCDNDRp73zx\\nkEA1PNs6Qekg6fz/1JqEq9FR49oTre2QQdl+EPKj+Deb9/FuSWvBgw==\\n-----END PUBLIC KEY-----`

**Comment by MetacoinDeveloperTeam** [comment]
Bitcoin or Ethereum addresses are PublicKeys, but Metacoin addresses are meaningless.

So, you can't generate an address while offline.

This avoids asset loss issues by transferring to an address that does not exist.


Please refer to the nodejs source code below for the error.

`
	const crypto = require('crypto');
	const axios = require('axios');

	var hostname = "https://testnetrest.metacoin.network:20923";
	function create_address() {
		return new Promise((resolve, reject) => {
			crypto.generateKeyPair("ec", {
				namedCurve: "secp384r1",  // or "secp521r1"
				publicKeyEncoding: {
					type: 'spki',
					format: 'pem'
				},
				privateKeyEncoding: {
					type: 'pkcs8',
					format: 'pem'
				}
			}, (err, public_key, private_key) => {
				if (err != null) {
					return reject(err.message);
				}

				axios.post(hostname + '/address', {
					'publickey': public_key
				})
					.then(function (response) {
						if (response.status != 200) {
							return Promise.reject("MTC server response errror");
						} else {
							return Promise.resolve(response.data);
						}
					})
					.then(function (mtc_address) {
						return resolve({ "Address": mtc_address, "publicKey": public_key, "PrivateKey": private_key });
					})
					.catch(function (error) {
						return reject(error);
					});
			});
		});
	}

	create_address()
		.then((v) => {
			console.log('Metacoin Address', v.Address);
			console.log('Public Key', v.publicKey);
			console.log('Private Key', v.PrivateKey);
		})
		.catch((err) => {
			console.log(err);
		});
`

**Comment by Wangmmx** [comment]
Thank you for your reply. I will try it. By the way, the hostname in the example you gave ` path:/address`. This is repeated below.

**Comment by MetacoinDeveloperTeam** [comment]
Oops!!

i fix it!
